# Generated by Django 3.0.7 on 2020-06-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200615_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('nif', models.DecimalField(decimal_places=0, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('zip_code', models.CharField(max_length=8)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('emission_date', models.DateField()),
                ('client_name', models.CharField(max_length=120)),
                ('client_nif', models.CharField(max_length=9)),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_nif', models.CharField(max_length=9)),
                ('service_value', models.PositiveIntegerField()),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('tax_explanation', models.TextField(blank=True)),
                ('service_date', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nif', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Fatura',
        ),
    ]
