# Generated by Django 3.0.7 on 2020-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200616_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_nif',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_nif',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
