# Generated by Django 3.0.7 on 2020-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200616_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fid',
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
